# Generated by Django 3.0.8 on 2020-07-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='description',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='image_detail',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='app',
            name='image_main',
        ),
        migrations.AddField(
            model_name='app',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
